[project]
name = "imo25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.4",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "ruff>=0.12.5",
]
